# Generated by Django 3.2.7 on 2021-10-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hostnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOSTNAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.IntegerField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='hostnames',
        ),
    ]
