# Generated by Django 3.2.7 on 2021-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211002_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostname',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
