# Generated by Django 3.2.7 on 2021-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211002_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
