# Generated by Django 3.2.7 on 2021-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hostname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
