# Generated by Django 3.2.7 on 2021-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hostname_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='phone',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
