# Generated by Django 3.2.7 on 2021-10-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPApp', '0003_filesupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesUpload',
        ),
    ]
