# Generated by Django 3.2.7 on 2021-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IPApp', '0004_delete_filesupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOST',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=30)),
                ('ipv4', models.CharField(blank=True, max_length=100)),
                ('ipv6', models.IntegerField(null=True)),
            ],
        ),
    ]
