# Generated by Django 3.2.7 on 2021-10-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPApp', '0005_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='ipv6',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
