# Generated by Django 3.2.7 on 2021-10-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPApp', '0006_auto_20211004_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ipv6',
        ),
    ]
