# Generated by Django 3.2.7 on 2021-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPApp', '0007_remove_host_ipv6'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ipv6',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
